- name: "type/blog"
  color: "71AAEB"
  description: "blog type"
- name: "type/paper"
  color: "0075ca"
  description: "paper type"
- name: "type/project"
  color: "cfd8d7"
  description: "project type"
- name: "type/course"
  color: "a22eef"
  description: "course type"
- name: "type/reading"
  color: "3702F6"
  description: "reading type"
- name: "type/feature"
  color: "4702D4"
  description: "feature type"
- name: "type/refactor"
  color: "6F09EB"
  description: "refactor type"
- name: "type/perf"
  color: "7902D4"
  description: "perf type"
