version: 1
labels:
  - label: "type/reading"
    title: "^reading.*"
  - label: "type/paper"
    title: "^paper.*"
  - label: "type/project"
    title: "^project.*"
  - label: "type/course"
    title: "^course.*"
  - label: "type/blog"
    title: "blog.*"
  - label: "type/feature"
    title: "^feat.*"
  - label: "type/fix"
    title: "^fix.*"
  - label: "type/refactor"
    title: "^refactor.*"
  - label: "type/style"
    title: "^style.*"
  - label: "type/chore"
    title: "^chore.*"
  - label: "type/perf"
    title: "^perf.*"
  - label: "type/build"
    title: "^build.*"
  - label: "type/revert"
    title: "^revert.*"
  - label: "component/ci"
    title: "^ci.*"
  - label: "component/test"
    title: "^test.*"
  - label: "component/doc"
    title: "^doc.*"
  - label: "type/design"
    titile: "^design.*"
